sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: nWTLk4UtIOs3SzoIpbQr9aGZW+6H95AoPZyMbZhyrxACchzgnddNzK3l5BDRKW2dJ/EhzzsR+yrtctQ/npuGU0VKIhh3aM+f/rf4yNGhcjFDbxUzZhirHajB7LzSaZj/AZeaQrCS4JsagJhVb2xTJatKl22Ron6W7Bf7JIRiV+zLCvYtQ1ZnPtl0IbkQnUOoex3mp2jOSGIDroj8hBYhpypRK7CZp2aOnhNBmfm5SWdCOTJ5f1yPx3q5rFQn4+gZ7ubBUe9Swnii+c6xRf/nOqXb6k4DyRRblGMqpjdcxNoGGJlyZEGBu/Vbc8Y9WqkYwridPGQrD7NxDyKsfX1bl3+05SFA/qjVn7WU9zIf7Op30UL0Nls2gWQtkGamV1skSG2x2VrEUEXHNrpYS0haW1u5Lq5epgd0h1CDKDl+/SQ5rt4F3uKAM5567b8v8ubb27aOP5Im9llFY1W3/NAQEXfYuMjXUpmTWBzwhVgHsGwo8jtQ+waAYGYMYx4/ClbOZbSuQyM298EaVs9GNngfVMHKPe29sluniPUErg63alHxV6AuaWSHhHc5ZX17Wq1WI+ukRmQMcDCU2IxL33C9kFlw+RtgxZzVVD0OxgMVjxFuuNm4OKtcaucyY6BJ+KGPV58IHpsC31JK6wWOLUr/STgR84i5JWLiG7KDhu/5p3o=
branches:
  only:
  - source
