sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: a4ky7gGRWq/ZDYmmnCCXwUwnKAd7kxVEJlfbk8/qxwZ/iJD/dGlsBzWKG1ViPPPEK5TQ34+ZNo9ByfGdRJgCmh5xxDV/OTyZUL+vPCcTZAILpFUgqCapM7KgY8zCRsPWeBIotFa4wpgXpdrOa+rYANVSTLRG3XvbCdwb62fLmexaemeaWuMHTLiXxL+4p2x4CnNlaCDpkIgacmeZlQ4T64DXdmVTvcuYdZViI3ahAl0z9o7ChGRxALyr1daRH7Rrr8jwxumehhW+8aYlnI6RSGRwxv/floaIp0uREcqr2t1eRgxEjyFpll9VlxVZJPmIyTNbkF5nw3K8UtOf7K4USJ6mAogqf8Oe7pyOOlQan2PiCwoeIlY9KA+avXjtfH0FIs5GfZkKK3/5PTs9D2K1+3j1mamJae99hNsP1gMVGIXNXNQ6jUFR/WM6kmthxjsPf+y04QIMJtW+3e5F8A6gHWOmODn7t8RiJTE8471O+BnwAorYpNgxurRcwDtPm7NUBD0G3IwMwCZkxSY94PN2sXJvFC0MbxzbKIZtxHQ7J0/N+EMCV36sVbbTIBvIOg3SpgYHuATTzD+eaZvErtqtVeuRFT/IWuc+oqDLMGA/z+I9YG6Eq/LzkrRaBE4uJBiojp+GNL22VEO35l1PiNmnoucZRiBsU+pq+ynmXyC6cbY=
  - secure: dGPNgWGmjKXJ2aYXDnhdWhQEUKRJ8iufEYi/kNmRUT51sMAO3Gse3SpRVf/TZrU+vs/XpwzgikF2EsA5XbDpMnmCucUAXn2Qg7qcQRlXTnGBFIlMuL/iCiHEtzzIDSAfSUnvQ/bjUlo4eqaPs8bkY9N9GQk1jOKUetTJYCPdV3jaSniAJBs0DygCadFHQkxu2nBEDfIOoco+gg/ZckymnuLhlRMWn2udiS51pGC9a1A078psCX/IflOtu8fRAeZRv3dBp4Qr68doVc8OdHGdL62Wvjpcka6y45rQHSD5lD/8B+sE4tRr8F1xMcGDU2j9V57kOpGPxMDTR5tambJ9XTkQ79DGjuz9blRTpbdfjqmaV1Hgpi/On9RvhD1DSpylN0VfzTR3hTSFt47JfqeTw/V8u2HZK22yF6qsD70Jys7DnbLLJ3/ey2B65GW3ih6MsiI4mfNsY4ZgICKMns+n2c2Ib6Xn1ChWtCHyIeCC/TGZoV0cq+Rnfq81Rc7fcGrBXOVz42JnCX3tcRS32OK/PoNByrfSFWRL9WcPXSQ7BM57c8MXNpvoy/PdDS8mx+2tYO+ygwhVOf5FV5RcVskP9OYlknqOvVDc4SGabk5404zXVM/wIvJwPbAFKRAXlygkSwnq3FHqzBfZimni5N+IsK84/URc30JtsD0Mev5y+7s=
branches:
  only:
  - source
