sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: runL2gz1uN+VlCpsz0OuHV/LzuE5bo2QUdtiXvqXjGdcnU+ccNwRknLIVZ+T7ISnRnmDpqt15Sx++Y3EEdO53AngaUJeJ1e7j/U8tmG+Vpmsbj8e5HSvBsblErXOx+hdv7jkZZ3rgrHlHByJYPMcz9KUkd3/CZ67q/bqJF+M0K0t0kghcshHqY71Mj0cbp2VE7m2JX1VA5lzlPTgbxPzQTJzrHE5Zs6/DbGfKfSIecD0JyGVvgFug6fVh0HC5iHhpgsm/+pqyfa8f/xumrsj1yuPP9LH9STIeAfAQaLheJowyiPg0Bw6A/tW/pEi057sSze+ReeCnpueS6yVMnxQDOfL7eXPvBUlRACVB8HEfxiZERdYMoliXo+KD9eFyKYTH9MA0HNwj37SVw22XZG9xvJowhf7SLe6aKAes6f2TJl8hLALGY2q4KsvfAO6FnnK2N7otX/i4WqxLGvRADkPOnipWAMWKgnZSCX6pIkYrF8ByBW+oIw3UPIcxl1j9t54nUGX5plrX5B5YLeNoV1wG8TQUbMSFYEUDFz24w6YdJMN/LNmlBR+YZM7tVb22l7Idm+3vys3rS8mkhYu90KTK7hMxVnUKDVu2/tdnad9ZBgIJKQHENsEAYHXcckemIrK05eLtguvjYeIpg/EOokIGguc/Jv5QLVeLQBA6y9B1vw=
branches:
  only:
  - master
